name: "Publish Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for macOS x86_64
            args: "--target x86_64-apple-darwin"
          - platform: "macos-latest" # for macOS aarch64
            args: "--target aarch64-apple-darwin"
          - platform: "ubuntu-22.04" # for Linux
            args: ""
          - platform: "windows-latest" # for Windows
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's safe to always install them
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: |
          cd appnotas-v2
          npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "AppNotas v__VERSION__"
          releaseBody: "See the assets, to download the latest version."
          releaseDraft: true
          prerelease: false
          projectPath: "appnotas-v2"
          args: ${{ matrix.args }}
